production:
  clients:
    default:
      database: rails2gaijin_production
      hosts:
        - localhost:27017
      options:

development:
  clients:
    default:
      database: rails2gaijin_development
      hosts:
        - localhost:27017
      options:    
  options:
    
test:
  clients:
    default:
      database: rails2gaijin_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1